<b> Data exploration using Pandas </b>

In [1]:
import pandas as pd
import numpy as np

Tasks at hand :

    - import the dataset
    - clean, format if needed
    - Grouping/ merging
    - Explore the results or findings

<b> Importing the dataset </b>

In [2]:
bikes = pd.read_csv("..//Bike-Sharing-Dataset//hour.csv")

In [3]:
type(bikes)

pandas.core.frame.DataFrame

In [4]:
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [5]:
bikes.tail()

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
17374           1           2  0.26  0.2576  0.60     0.1642      11   
17375           1           2  0.26  0.2576  0.60     0.1642       8   
17376           1           1  0.26  0.2576  0.60     0.1642       7   
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
17374         108  119  
17375          81   89  
17376          83   90  
17377          48   61  
17378          37   49

In [6]:
bikes.tail(2)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
17377          48   61  
17378          37   49

In [7]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     17379 non-null  int64  
 1   dteday      17379 non-null  object 
 2   season      17379 non-null  int64  
 3   yr          17379 non-null  int64  
 4   mnth        17379 non-null  int64  
 5   hr          17379 non-null  int64  
 6   holiday     17379 non-null  int64  
 7   weekday     17379 non-null  int64  
 8   workingday  17379 non-null  int64  
 9   weathersit  17379 non-null  int64  
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64  
 15  registered  17379 non-null  int64  
 16  cnt         17379 non-null  int64  
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


In [8]:
bikes.shape

(17379, 17)

In [9]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [10]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [11]:
# statistical data
bikes.describe()

instant        season            yr          mnth            hr  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000   
mean    8690.0000      2.501640      0.502561      6.537775     11.546752   
std     5017.0295      1.106918      0.500008      3.438776      6.914405   
min        1.0000      1.000000      0.000000      1.000000      0.000000   
25%     4345.5000      2.000000      0.000000      4.000000      6.000000   
50%     8690.0000      3.000000      1.000000      7.000000     12.000000   
75%    13034.5000      3.000000      1.000000     10.000000     18.000000   
max    17379.0000      4.000000      1.000000     12.000000     23.000000   

            holiday       weekday    workingday    weathersit          temp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.028770      3.003683      0.682721      1.425283      0.496987   
std        0.167165      2.005771      0.465431      0.639357      0.192556   
min        0.000000      0.000000      0.000000      1.000000      0.020000   
25%        0.000000      1.000000      0.000000      1.000000      0.340000   
50%        0.000000      3.000000      1.000000      1.000000      0.500000   
75%        0.000000      5.000000      1.000000      2.000000      0.660000   
max        1.000000      6.000000      1.000000      4.000000      1.000000   

              atemp           hum     windspeed        casual    registered  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.475775      0.627229      0.190098     35.676218    153.786869   
std        0.171850      0.192930      0.122340     49.305030    151.357286   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.333300      0.480000      0.104500      4.000000     34.000000   
50%        0.484800      0.630000      0.194000     17.000000    115.000000   
75%        0.621200      0.780000      0.253700     48.000000    220.000000   
max        1.000000      1.000000      0.850700    367.000000    886.000000   

                cnt  
count  17379.000000  
mean     189.463088  
std      181.387599  
min        1.000000  
25%       40.000000  
50%      142.000000  
75%      281.000000  
max      977.000000

In [12]:
bikes.describe

<bound method NDFrame.describe of        instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81    

In [13]:
bikes.season.describe()

count    17379.000000
mean         2.501640
std          1.106918
min          1.000000
25%          2.000000
50%          3.000000
75%          3.000000
max          4.000000
Name: season, dtype: float64

<b> Cleaning and formatting the data frame </b>

In [14]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [15]:
bikes.instant.unique()

array([    1,     2,     3, ..., 17377, 17378, 17379])

In [16]:
bikes.dteday.unique()

array(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
       '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
       '2011-01-09', '2011-01-10', '2011-01-11', '2011-01-12',
       '2011-01-13', '2011-01-14', '2011-01-15', '2011-01-16',
       '2011-01-17', '2011-01-18', '2011-01-19', '2011-01-20',
       '2011-01-21', '2011-01-22', '2011-01-23', '2011-01-24',
       '2011-01-25', '2011-01-26', '2011-01-27', '2011-01-28',
       '2011-01-29', '2011-01-30', '2011-01-31', '2011-02-01',
       '2011-02-02', '2011-02-03', '2011-02-04', '2011-02-05',
       '2011-02-06', '2011-02-07', '2011-02-08', '2011-02-09',
       '2011-02-10', '2011-02-11', '2011-02-12', '2011-02-13',
       '2011-02-14', '2011-02-15', '2011-02-16', '2011-02-17',
       '2011-02-18', '2011-02-19', '2011-02-20', '2011-02-21',
       '2011-02-22', '2011-02-23', '2011-02-24', '2011-02-25',
       '2011-02-26', '2011-02-27', '2011-02-28', '2011-03-01',
       '2011-03-02', '2011-03-03', '2011-03-04', '2011-

In [17]:
bikes.season.unique()

array([1, 2, 3, 4])

In [18]:
bikes.yr.unique()

array([0, 1])

In [19]:
bikes["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
bikes.hr.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
bikes.holiday.unique()

array([0, 1])

In [22]:
bikes.weekday.unique()

array([6, 0, 1, 2, 3, 4, 5])

In [23]:
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [24]:
bikes.sum()

instant                                               151023510
dteday        2011-01-012011-01-012011-01-012011-01-012011-0...
season                                                    43476
yr                                                         8734
mnth                                                     113620
hr                                                       200671
holiday                                                     500
weekday                                                   52201
workingday                                                11865
weathersit                                                24770
temp                                                    8637.14
atemp                                                 8268.4955
hum                                                    10900.61
windspeed                                             3303.7063
casual                                                   620017
registered                              

In [25]:
bikes.isnull()

instant  dteday  season     yr   mnth     hr  holiday  weekday  \
0        False   False   False  False  False  False    False    False   
1        False   False   False  False  False  False    False    False   
2        False   False   False  False  False  False    False    False   
3        False   False   False  False  False  False    False    False   
4        False   False   False  False  False  False    False    False   
...        ...     ...     ...    ...    ...    ...      ...      ...   
17374    False   False   False  False  False  False    False    False   
17375    False   False   False  False  False  False    False    False   
17376    False   False   False  False  False  False    False    False   
17377    False   False   False  False  False  False    False    False   
17378    False   False   False  False  False  False    False    False   

       workingday  weathersit   temp  atemp    hum  windspeed  casual  \
0           False       False  False  False  False      False   False   
1           False       False  False  False  False      False   False   
2           False       False  False  False  False      False   False   
3           False       False  False  False  False      False   False   
4           False       False  False  False  False      False   False   
...           ...         ...    ...    ...    ...        ...     ...   
17374       False       False  False  False  False      False   False   
17375       False       False  False  False  False      False   False   
17376       False       False  False  False  False      False   False   
17377       False       False  False  False  False      False   False   
17378       False       False  False  False  False      False   False   

       registered    cnt  
0           False  False  
1           False  False  
2           False  False  
3           False  False  
4           False  False  
...           ...    ...  
17374       False  False  
17375       False  False  
17376       False  False  
17377       False  False  
17378       False  False  

[17379 rows x 17 columns]

In [26]:
bikes.instant.isnull()

0        False
1        False
2        False
3        False
4        False
         ...  
17374    False
17375    False
17376    False
17377    False
17378    False
Name: instant, Length: 17379, dtype: bool

In [27]:
bikes.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
17374    False
17375    False
17376    False
17377    False
17378    False
Length: 17379, dtype: bool

In [28]:
bikes.duplicated().sum()

0

In [29]:
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [30]:
bikes.drop_duplicates(subset="instant", inplace=True)

In [31]:
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [32]:
# create and add a new series to this data frame

In [33]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [34]:
bikes.shape

(17379, 17)

<b> create and add a new column to a dataframe </b>

In [35]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [36]:
bikes.head(3)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32

In [37]:
dte = pd.to_datetime(bikes.dteday)

In [38]:
type(dte)

pandas.core.series.Series

In [39]:
dte

0       2011-01-01
1       2011-01-01
2       2011-01-01
3       2011-01-01
4       2011-01-01
           ...    
17374   2012-12-31
17375   2012-12-31
17376   2012-12-31
17377   2012-12-31
17378   2012-12-31
Name: dteday, Length: 17379, dtype: datetime64[ns]

In [40]:
dte.dt.month

0         1
1         1
2         1
3         1
4         1
         ..
17374    12
17375    12
17376    12
17377    12
17378    12
Name: dteday, Length: 17379, dtype: int64

In [41]:
dte.dt.year

0        2011
1        2011
2        2011
3        2011
4        2011
         ... 
17374    2012
17375    2012
17376    2012
17377    2012
17378    2012
Name: dteday, Length: 17379, dtype: int64

In [42]:
year = dte.dt.year

In [43]:
type(year)

pandas.core.series.Series

In [44]:
year

0        2011
1        2011
2        2011
3        2011
4        2011
         ... 
17374    2012
17375    2012
17376    2012
17377    2012
17378    2012
Name: dteday, Length: 17379, dtype: int64

In [45]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [46]:
bikes["year"]=year

In [47]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'year'],
      dtype='object')

In [48]:
bikes.head(3)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  year  
0           1  0.24  0.2879  0.81        0.0       3          13   16  2011  
1           1  0.22  0.2727  0.80        0.0       8          32   40  2011  
2           1  0.22  0.2727  0.80        0.0       5          27   32  2011

In [49]:
bikes.shape

(17379, 18)

In [50]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
year            int64
dtype: object

In [51]:
# remove a series from dataframe

In [52]:
bikes = bikes.drop("instant",axis=1)

In [53]:
bikes

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0      2011-01-01       1   0     1   0        0        6           0   
1      2011-01-01       1   0     1   1        0        6           0   
2      2011-01-01       1   0     1   2        0        6           0   
3      2011-01-01       1   0     1   3        0        6           0   
4      2011-01-01       1   0     1   4        0        6           0   
...           ...     ...  ..   ...  ..      ...      ...         ...   
17374  2012-12-31       1   1    12  19        0        1           1   
17375  2012-12-31       1   1    12  20        0        1           1   
17376  2012-12-31       1   1    12  21        0        1           1   
17377  2012-12-31       1   1    12  22        0        1           1   
17378  2012-12-31       1   1    12  23        0        1           1   

       weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  \
0               1  0.24  0.2879  0.81     0.0000       3          13   16   
1               1  0.22  0.2727  0.80     0.0000       8          32   40   
2               1  0.22  0.2727  0.80     0.0000       5          27   32   
3               1  0.24  0.2879  0.75     0.0000       3          10   13   
4               1  0.24  0.2879  0.75     0.0000       0           1    1   
...           ...   ...     ...   ...        ...     ...         ...  ...   
17374           2  0.26  0.2576  0.60     0.1642      11         108  119   
17375           2  0.26  0.2576  0.60     0.1642       8          81   89   
17376           1  0.26  0.2576  0.60     0.1642       7          83   90   
17377           1  0.26  0.2727  0.56     0.1343      13          48   61   
17378           1  0.26  0.2727  0.65     0.1343      12          37   49   

       year  
0      2011  
1      2011  
2      2011  
3      2011  
4      2011  
...     ...  
17374  2012  
17375  2012  
17376  2012  
17377  2012  
17378  2012  

[17379 rows x 17 columns]

In [54]:
bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'year'],
      dtype='object')

<b> Group / Merging </b>

In [55]:
bikes.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1   0        0        6           0           1   
1  2011-01-01       1   0     1   1        0        6           0           1   
2  2011-01-01       1   0     1   2        0        6           0           1   
3  2011-01-01       1   0     1   3        0        6           0           1   
4  2011-01-01       1   0     1   4        0        6           0           1   

   temp   atemp   hum  windspeed  casual  registered  cnt  year  
0  0.24  0.2879  0.81        0.0       3          13   16  2011  
1  0.22  0.2727  0.80        0.0       8          32   40  2011  
2  0.22  0.2727  0.80        0.0       5          27   32  2011  
3  0.24  0.2879  0.75        0.0       3          10   13  2011  
4  0.24  0.2879  0.75        0.0       0           1    1  2011

In [56]:
bikes_2011 = bikes[year==2011]

In [57]:
bikes_2011.shape

(8645, 17)

In [58]:
bikes_2011

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0     2011-01-01       1   0     1   0        0        6           0   
1     2011-01-01       1   0     1   1        0        6           0   
2     2011-01-01       1   0     1   2        0        6           0   
3     2011-01-01       1   0     1   3        0        6           0   
4     2011-01-01       1   0     1   4        0        6           0   
...          ...     ...  ..   ...  ..      ...      ...         ...   
8640  2011-12-31       1   0    12  19        0        6           0   
8641  2011-12-31       1   0    12  20        0        6           0   
8642  2011-12-31       1   0    12  21        0        6           0   
8643  2011-12-31       1   0    12  22        0        6           0   
8644  2011-12-31       1   0    12  23        0        6           0   

      weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  year  
0              1  0.24  0.2879  0.81     0.0000       3          13   16  2011  
1              1  0.22  0.2727  0.80     0.0000       8          32   40  2011  
2              1  0.22  0.2727  0.80     0.0000       5          27   32  2011  
3              1  0.24  0.2879  0.75     0.0000       3          10   13  2011  
4              1  0.24  0.2879  0.75     0.0000       0           1    1  2011  
...          ...   ...     ...   ...        ...     ...         ...  ...   ...  
8640           1  0.42  0.4242  0.54     0.2239      19          73   92  2011  
8641           1  0.42  0.4242  0.54     0.2239       8          63   71  2011  
8642           1  0.40  0.4091  0.58     0.1940       2          50   52  2011  
8643           1  0.38  0.3939  0.62     0.1343       2          36   38  2011  
8644           1  0.36  0.3788  0.66     0.0000       4          27   31  2011  

[8645 rows x 17 columns]

In [60]:
bikes_2011.count()

dteday        8645
season        8645
yr            8645
mnth          8645
hr            8645
holiday       8645
weekday       8645
workingday    8645
weathersit    8645
temp          8645
atemp         8645
hum           8645
windspeed     8645
casual        8645
registered    8645
cnt           8645
year          8645
dtype: int64

In [67]:
bikes_2012 = bikes[year==2012]

In [71]:
bikes_2011 = bikes[year==2011]

In [72]:
bikes_2011.shape

(8645, 17)

In [73]:
bikes_2012.shape

(8734, 17)

<b> Grouping </b>

In [74]:
df_by_season = bikes.groupby("season")

In [75]:
type(df_by_season)

pandas.core.groupby.generic.DataFrameGroupBy

In [77]:
df_by_season

In [78]:
df_by_season.casual.sum()

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [79]:
df_by_season.registered.sum()

season
1    410726
2    715067
3    835038
4    711831
Name: registered, dtype: int64

In [81]:
df_by_season.registered.sum().max()

835038

In [82]:
# concatenation

series_casual = df_by_season.casual.sum()
series_registered = df_by_season.registered.sum()
frames = [series_casual, series_registered]

In [83]:
type(frames)

list

In [84]:
type(series_casual)

pandas.core.series.Series

In [85]:
type(series_registered)

pandas.core.series.Series

In [86]:
df = pd.concat(frames, axis=1) # combine them column-wise

In [87]:
df

casual  registered
season                    
1        60622      410726
2       203522      715067
3       226091      835038
4       129782      711831

In [88]:
# add a new series to above data frame
df["total"] = df.casual + df.registered

In [89]:
df

casual  registered    total
season                             
1        60622      410726   471348
2       203522      715067   918589
3       226091      835038  1061129
4       129782      711831   841613

In [90]:
df.to_csv("outcomeBySeason.csv")

<b> merge </b>

In [91]:
series_casual

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [92]:
series_registered

season
1    410726
2    715067
3    835038
4    711831
Name: registered, dtype: int64

In [93]:
df_casual = pd.DataFrame(series_casual)

In [94]:
df_registered = pd.DataFrame(series_registered)

In [95]:
df_casual

casual
season        
1        60622
2       203522
3       226091
4       129782

In [96]:
df_registered

registered
season            
1           410726
2           715067
3           835038
4           711831

In [97]:
df2 = pd.merge(df_casual, df_registered, on="season")

In [98]:
df2

casual  registered
season                    
1        60622      410726
2       203522      715067
3       226091      835038
4       129782      711831